package entities;
// Generated Jun 6, 2018 5:08:14 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Aspnetuserclaims generated by hbm2java
 */
@Entity
@Table(name = "aspnetuserclaims", catalog = "vasp")
public class Aspnetuserclaims implements java.io.Serializable {

	private Integer id;
	private Aspnetusers aspnetusers;
	private String claimType;
	private String claimValue;

	public Aspnetuserclaims() {
	}

	public Aspnetuserclaims(Aspnetusers aspnetusers) {
		this.aspnetusers = aspnetusers;
	}

	public Aspnetuserclaims(Aspnetusers aspnetusers, String claimType, String claimValue) {
		this.aspnetusers = aspnetusers;
		this.claimType = claimType;
		this.claimValue = claimValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false)
	public Aspnetusers getAspnetusers() {
		return this.aspnetusers;
	}

	public void setAspnetusers(Aspnetusers aspnetusers) {
		this.aspnetusers = aspnetusers;
	}

	@Column(name = "ClaimType")
	public String getClaimType() {
		return this.claimType;
	}

	public void setClaimType(String claimType) {
		this.claimType = claimType;
	}

	@Column(name = "ClaimValue")
	public String getClaimValue() {
		return this.claimValue;
	}

	public void setClaimValue(String claimValue) {
		this.claimValue = claimValue;
	}

}
