package entities;
// Generated Jun 6, 2018 5:08:14 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Aspnetuserlogins generated by hbm2java
 */
@Entity
@Table(name = "aspnetuserlogins", catalog = "vasp")
public class Aspnetuserlogins implements java.io.Serializable {

	private AspnetuserloginsId id;
	private Aspnetusers aspnetusers;

	public Aspnetuserlogins() {
	}

	public Aspnetuserlogins(AspnetuserloginsId id, Aspnetusers aspnetusers) {
		this.id = id;
		this.aspnetusers = aspnetusers;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "loginProvider", column = @Column(name = "LoginProvider", nullable = false, length = 128)),
			@AttributeOverride(name = "providerKey", column = @Column(name = "ProviderKey", nullable = false, length = 128)),
			@AttributeOverride(name = "userId", column = @Column(name = "UserId", nullable = false, length = 128)) })
	public AspnetuserloginsId getId() {
		return this.id;
	}

	public void setId(AspnetuserloginsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false, insertable = false, updatable = false)
	public Aspnetusers getAspnetusers() {
		return this.aspnetusers;
	}

	public void setAspnetusers(Aspnetusers aspnetusers) {
		this.aspnetusers = aspnetusers;
	}

}
