package entities;
// Generated Jun 6, 2018 5:08:14 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Donations generated by hbm2java
 */
@Entity
@Table(name = "donations", catalog = "vasp")
public class Donations implements java.io.Serializable {

	private Integer donationId;
	private Aspnetusers aspnetusers;
	private Fundraisingcampaigns fundraisingcampaigns;
	private int amount;

	public Donations() {
	}

	public Donations(int amount) {
		this.amount = amount;
	}

	public Donations(Aspnetusers aspnetusers, Fundraisingcampaigns fundraisingcampaigns, int amount) {
		this.aspnetusers = aspnetusers;
		this.fundraisingcampaigns = fundraisingcampaigns;
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DonationId", unique = true, nullable = false)
	public Integer getDonationId() {
		return this.donationId;
	}

	public void setDonationId(Integer donationId) {
		this.donationId = donationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Volunteer_Id")
	public Aspnetusers getAspnetusers() {
		return this.aspnetusers;
	}

	public void setAspnetusers(Aspnetusers aspnetusers) {
		this.aspnetusers = aspnetusers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Campaign_CampaignId")
	public Fundraisingcampaigns getFundraisingcampaigns() {
		return this.fundraisingcampaigns;
	}

	public void setFundraisingcampaigns(Fundraisingcampaigns fundraisingcampaigns) {
		this.fundraisingcampaigns = fundraisingcampaigns;
	}

	@Column(name = "Amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

}
