package entities;
// Generated Jun 6, 2018 5:08:14 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fundraisingcampaigns generated by hbm2java
 */
@Entity
@Table(name = "fundraisingcampaigns", catalog = "vasp")
public class Fundraisingcampaigns implements java.io.Serializable {

	private Integer campaignId;
	private String name;
	private String description;
	private Date startDate;
	private Date endDate;
	private int targetAmount;
	private Set<Donations> donationses = new HashSet<Donations>(0);

	public Fundraisingcampaigns() {
	}

	public Fundraisingcampaigns(String name, String description, Date startDate, Date endDate, int targetAmount) {
		this.name = name;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
		this.targetAmount = targetAmount;
	}

	public Fundraisingcampaigns(String name, String description, Date startDate, Date endDate, int targetAmount,
			Set<Donations> donationses) {
		this.name = name;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
		this.targetAmount = targetAmount;
		this.donationses = donationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CampaignId", unique = true, nullable = false)
	public Integer getCampaignId() {
		return this.campaignId;
	}

	public void setCampaignId(Integer campaignId) {
		this.campaignId = campaignId;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "TargetAmount", nullable = false)
	public int getTargetAmount() {
		return this.targetAmount;
	}

	public void setTargetAmount(int targetAmount) {
		this.targetAmount = targetAmount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fundraisingcampaigns")
	public Set<Donations> getDonationses() {
		return this.donationses;
	}

	public void setDonationses(Set<Donations> donationses) {
		this.donationses = donationses;
	}

}
